name: CI
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  pull_request:
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Doctrine ${{ matrix.doctrine }}
    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2']
        laravel: ['8', '9']
        doctrine: ['2.11', '2.12', '2.13', '2.14']
        exclude:
          - php: '8.2'
            laravel: '8'
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: phpunit, git

      - name: Install Composer dependencies
        run: rm -f composer.lock

      - name: Install dependencies for Laravel ${{ matrix.laravel}}
        run: composer require --no-progress --no-scripts --no-plugins illuminate/auth ^${{ matrix.laravel }} illuminate/config ^${{ matrix.laravel }} illuminate/contracts ^${{ matrix.laravel }} illuminate/support ^${{ matrix.laravel }} doctrine/orm ~${{ matrix.doctrine }}.0 -v

      - name: Update dependencies
        run: composer update --no-interaction

      - name: PHPUnit
        run: vendor/bin/phpunit
