name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: 'ubuntu-latest'
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Doctrine ${{ matrix.doctrine }}
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1']
        laravel: ['6', '7', '8', '9']
        doctrine: ['2.8', '2.9', '2.10', '2.11']
        exclude:
          - php: '7.2'
            laravel: '8'
          - php: '7.2'
            laravel: '9'
          - php: '7.3'
            laravel: '9'
          - php: '7.4'
            laravel: '9'
          - php: '8.1'
            laravel: '6'
          - php: '8.1'
            laravel: '7'
          - laravel: '9'
            doctrine: '2.8'
          - laravel: '9'
            doctrine: '2.9'
          - laravel: '9'
            doctrine: '2.10'
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit, git

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "php-${{ matrix.php }}-${{matrix.laravel}}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php }}-${{matrix.laravel}}-composer-locked-"

      - name: Install Composer dependencies
        run: rm -f composer.lock

      - name: Install dependencies for Laravel ${{ matrix.laravel}}
        run: composer require --no-progress --no-scripts --no-plugins illuminate/auth ^${{ matrix.laravel }} illuminate/config ^${{ matrix.laravel }} illuminate/contracts ^${{ matrix.laravel }} illuminate/support ^${{ matrix.laravel }} doctrine/orm ~${{ matrix.doctrine }}.0 -v

      - name: Update dependencies
        run: composer update --no-interaction

      - name: PHPUnit
        run: vendor/bin/phpunit
